name: Release

on:
  workflow_dispatch:

jobs:
  release:
    uses: guardian/gha-scala-library-release-workflow/.github/workflows/reusable-release.yml@attest
    permissions: { contents: write, pull-requests: write, id-token: write, attestations: write }
    with:
      GITHUB_APP_ID: 1072408
      SONATYPE_PROFILE_NAME: 'com.madgag'
      SONATYPE_CREDENTIAL_HOST: 's01.oss.sonatype.org'
    secrets:
      SONATYPE_TOKEN: ${{ secrets.AUTOMATED_MAVEN_RELEASE_SONATYPE_TOKEN }}
      PGP_PRIVATE_KEY: ${{ secrets.AUTOMATED_MAVEN_RELEASE_PGP_SECRET }}
      GITHUB_APP_PRIVATE_KEY: ${{ secrets.AUTOMATED_MAVEN_RELEASE_GITHUB_APP_PRIVATE_KEY }}
